title: Simone Locatelli
#logo: /assets/img/headshot_circle.png
description: **Location:** Italy | **Email:** [simoloc@gmail.com](mailto:simoloc@gmail.com) | **LinkedIn:** [linkedin.com/in/simone-locatelli-386b94113](https://www.linkedin.com/in/simone-locatelli-386b94113)
#show_downloads: true
theme: jekyll-theme-minimal
